"""update non-null of document in works table

Revision ID: 4a908d10b459
Revises: 360c65a62392
Create Date: 2024-11-21 16:40:56.966690

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a908d10b459'
down_revision: Union[str, None] = '360c65a62392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'initial_document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('works', 'primary_document_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('works', 'primary_document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('works', 'initial_document_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
