"""Create funder column

Revision ID: 4d66a5dc782b
Revises: 845c59592898
Create Date: 2024-12-01 20:47:57.932627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d66a5dc782b'
down_revision: Union[str, None] = '845c59592898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rtransparent_publication', sa.Column('funder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rtransparent_publication', 'funder')
    # ### end Alembic commands ###
