"""add field in OddPub is nullable

Revision ID: 600039d1785e
Revises: 832c238c1be7
Create Date: 2024-12-13 17:00:30.689184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '600039d1785e'
down_revision: Union[str, None] = '832c238c1be7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oddpub_metrics', 'article',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('oddpub_metrics', 'is_open_data',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('oddpub_metrics', 'is_reuse',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('oddpub_metrics', 'is_open_code',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('oddpub_metrics', 'is_open_data_das',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('oddpub_metrics', 'is_open_code_cas',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oddpub_metrics', 'is_open_code_cas',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('oddpub_metrics', 'is_open_data_das',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('oddpub_metrics', 'is_open_code',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('oddpub_metrics', 'is_reuse',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('oddpub_metrics', 'is_open_data',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('oddpub_metrics', 'article',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
