"""Create RTransparentPublication workd_id and doc id is nullable

Revision ID: 845c59592898
Revises: 74f7f1590fb6
Create Date: 2024-11-29 17:13:01.858245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845c59592898'
down_revision: Union[str, None] = '74f7f1590fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'hash_data',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('rtransparent_publication', 'work_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rtransparent_publication', 'provenance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rtransparent_publication', 'provenance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rtransparent_publication', 'work_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'hash_data',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
