FROM python:3.11-slim

WORKDIR /app

COPY . /app

RUN pip install --no-cache-dir poetry

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    r-base \
    r-base-dev \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

ENV R_HOME=/usr/lib/R

RUN R -e "install.packages('devtools')"

RUN R -e "devtools::install_github('quest-bih/oddpub')"

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

EXPOSE 80

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
