# Use the official Python image as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install Poetry
RUN pip install --no-cache-dir poetry

# Install R and its dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    r-base \
    r-base-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set R_HOME environment variable
ENV R_HOME=/usr/lib/R

# Install dependencies using Poetry
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi

# Make port 80 available to the world outside this container
EXPOSE 80

# Run app.py when the container launches
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
