services:
  postgres:
    platform: linux/amd64
    image: postgres:15
    container_name: postgres_db
    env_file: "../.env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s  # Added missing timeout value
      retries: 5

  oddpub:
    build:
      context: ../services/oddpub
      dockerfile: Dockerfile
    container_name: oddpub_service
    ports:
      - "8071:8071"

volumes:
  postgres_data:
